<?php

namespace WS\AdminLTEBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TopRecetteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopRecetteRepository extends EntityRepository
{
}
